version: 2
updates:
  - package-ecosystem: "pip"
    directory: "smoke-tests/client/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "Flask"
      - dependency-name: "requests"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "smoke-tests/runner/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "Flask"
      - dependency-name: "requests"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "smoke-tests/tests/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "pytest"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "test-engineering/contract-tests/partner/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "test-engineering/contract-tests/client/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "test-engineering/load/"
    schedule:
      interval: "monthly"
    commit-message:
      # Run the load test when updating load test dependency
      prefix: "chore(deps) [load test: abort]"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
