version: 2.1

jobs:
  run_checks:
    docker:
      - image: python:3.8
    working_directory: "~/project/<< parameters.component >>"
    parameters:
      tox_env:
        type: string
      component:
        type: string
    steps:
      - checkout:
          path: ~/project/
      - run:
          name: Install tox
          command: |
            python -m pip install --upgrade pip
            python -m pip install tox
      - run:
          name: Run tox
          command: |
            tox -e << parameters.tox_env >>

workflows:
  version: 2
  build:
    jobs:
      - run_checks:
          name: Run << matrix.tox_env >> checks for client 🤖
          component: client
          matrix:
            parameters:
              tox_env: [black, flake8, mypy]
      - run_checks:
          name: Run << matrix.tox_env >> checks for partner 📋
          component: partner
          matrix:
            parameters:
              tox_env: [black, flake8, mypy, py38]
