version: 2
updates:
  - package-ecosystem: "pip"
    directory: "partner/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "Dependabot"
      - "dependencies"
      - "partner"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "client/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "Dependabot"
      - "dependencies"
      - "client"
    open-pull-requests-limit: 10
