[advisories]
ignore = [
    "RUSTSEC-2020-0041", # Bound by Sentry 0.19 requiring Hyper 0.13
    "RUSTSEC-2021-0078", # Bound by Sentry 0.19 requiring Hyper 0.13
    "RUSTSEC-2021-0079", # Bound by Sentry 0.19 requiring Hyper 0.13

    # time 0.1.43 still in use by chrono
    "RUSTSEC-2020-0071", # Time 0.14.3 - Potential segfault in time crate.
    "RUSTSEC-2020-0159", # Chrono 0.4.19 - Potential segfault in `localtime_r` invokations.
]
