apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: [WORKER_COUNT]
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: gcr.io/[PROJECT_ID]/locust-contile:[LOCUST_IMAGE_TAG]
          env:
            - name: LOCUST_MODE_WORKER
              value: "true"
            - name: LOCUST_MASTER_NODE_HOST
              value: locust-master
            - name: TARGET_HOST
              value:
            - name: LOCUST_LOGLEVEL
              value:
            - name: CONTILE_LOCATION_TEST_HEADER
              value:
