apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-master
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: gcr.io/[PROJECT_ID]/locust-contile:[LOCUST_IMAGE_TAG]
          env:
            - name: LOCUST_MODE_MASTER
              value: "true"
            - name: TARGET_HOST
              value:
            - name: LOCUST_CSV
              value:
            - name: LOCUST_HOST
              value:
            - name: LOCUST_USERS
              value:
            - name: LOCUST_SPAWN_RATE
              value:
            - name: LOCUST_RUN_TIME
              value:
            - name: LOCUST_LOGLEVEL
              value:
            - name: CONTILE_LOCATION_TEST_HEADER
              value:
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
