apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-master
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: gcr.io/[PROJECT_ID]/locust-contile:[LOCUST_IMAGE_TAG]
          env:
            - name: LOCUST_MODE_MASTER
              value: "true"
            - name: TARGET_HOST
              value: [TARGET_HOST]
            - name: LOCUST_CSV
              value: [LOCUST_CSV]
            - name: LOCUST_HOST
              value: [LOCUST_HOST]
            - name: LOCUST_USERS
              value: "[LOCUST_USERS]"
            - name: LOCUST_SPAWN_RATE
              value: "[LOCUST_SPAWN_RATE]"
            - name: LOCUST_RUN_TIME
              value: "[LOCUST_RUN_TIME]"
            - name: LOCUST_LOGLEVEL
              value: [LOCUST_LOGLEVEL]
            - name: CONTILE_LOCATION_TEST_HEADER
              value: [CONTILE_LOCATION_TEST_HEADER]
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
