version: "3"
services:
  locust_master:
    image: locust
    build: .
    container_name: locust_master
    ports:
      - "8089:8089"
    environment:
      LOCUST_HOST: "https://localhost:8000"
      LOCUST_USERS: "200"
      LOCUST_SPAWN_RATE: "3"
      LOCUST_RUN_TIME: "10m"
      LOCUST_LOGLEVEL: "INFO"
      CONTILE_LOCATION_TEST_HEADER: "X-Test-Location"
    command: >
      --master --class-picker

  locust_worker:
    image: locust
    build: .
    environment:
      LOCUST_MASTER_NODE_HOST: locust_master
      LOCUST_LOGLEVEL: "INFO"
      CONTILE_LOCATION_TEST_HEADER: "X-Test-Location"
    command: >
      --worker
